application: ouroborothon
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /editor/.*
  script: blogs.editor
  login: admin

- url: /static
  static_dir: static

- url: /.*
  script: blogs.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
